### ISSUE TITLE
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

### ISSUE THREAD

**Issue by bbhxwl** [johnthiriet/Xamarin.Android.Huawei.Hms#4]
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

**Comment by johnthiriet** [comment]
Thanks for showing interest in my work.

Concerning your request I highly suggest that you take a look at how to write bindings. There are some ressources on the web about that and I also started a series of post on my blog: [https://johnthiriet.com/xamarin-android-binding-library-preparation/](https://johnthiriet.com/xamarin-android-binding-library-preparation/). I am sure that by spending some time on this you will succeed in doing what you need and learn new skills by doing so.

If you happened to be blocked along the way, you can open a thread on Microsoft's forums or StackOverflow and share this link on Twitter or whatever other means so that people can take a look at your specific issue and help you. Just don't ask them to do your work for you.

Unfortunately, as your request has nothing to do with HMS bindings, I will close the issue.

I wish you a great success in what you are trying to achieve.

Kind regards

John
